server:
  port: 9002

spring:
  application:
    name: nacos-consumer-example
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:example.yml