server:
  port: 8081

spring:
  application:
    name: websocket-server
  cloud:
    nacos:
      # Nacos 作为注册中心
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: websocket-namespace
        enabled: true
#      # Nacos作为配置中心
      config:
        server-addr: 127.0.0.1:8848
        namespace: NAMESPACE
        group: GROUP # 配置分组名称

management:
  endpoints:
    web:
      exposure:
        include: '*'

