server:
  port: 9090

spring:
  application:
    name: websocket-client.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        name: websocket-client.yml
        group: DEFAULT_GROUP

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: '*'

